from selenium.webdriver.common.by import By


class LoginPageLocators:
    EMAIL = (By.ID, ':r0:')
    PASSWORD = (By.ID, ':r1:')
    BUTTON_LOGIN = (By.CSS_SELECTOR, '#login-button')
    CREEATE_NEW_ORGANIZ = (By.CSS_SELECTOR, '#root > div.App > div > div.login__input-side > div.login__input-side__form > div.login__input-side__head.tb__text__light-black > a')
    FORGOT_PASS = (By.CSS_SELECTOR, '#root > div.App > div > div.login__input-side > div.login__input-side__form > div.login__input-side__form__data > div.forgot-password > p')
    AUTHORIZ_WITH_GOOGLE = (By.XPATH, '/html/body/div/div[2]/div/div[1]/div[2]/div[2]/button[2]')
    BUTTON_PERSONAL = (By.XPATH, '/html/body/div[1]/div[2]/div/div[1]/div/div[3]/div/div/button/div')
    LOGOUT = (By.XPATH, '/html/body/div[2]/div[3]/ul/li')


class RegistrationPageLocators:
    FIRST_NAME = (By.ID, ':r0:')
    LAST_NAME = (By.ID, ':r1:')
    EMAIL = (By.ID, ':r2:')
    COMPANY_NAME = (By.ID, ':r3:')
    PASSWORD = (By.ID, 'password_field')
    CHECK_BOX = (By.ID, 'marketing-accept-checkbox')
    BUTTON_CREATE = (By.ID, 'create-account')


class PlanningPageLocators:
    ADD_USER = (By.CSS_SELECTOR, '#root > div.App > div > div.planner-page__planner-control > div.control-bar-second-line__whitespace.left > div')
    CREATE_USER = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/button[1]')
    FIRST_NAME = (By.ID, 'firstName')
    LAST_NAME = (By.ID, 'lastName')
    USER_ROLE = (By.CSS_SELECTOR, '#mui-component-select-accountName')
    PLANNER = (By.CSS_SELECTOR, '#menu-accountName > div.MuiPaper-root.MuiPaper-elevation.MuiPaper-rounded.MuiPaper-elevation1.MuiMenu-paper.MuiPaper-root.MuiPaper-elevation.MuiPaper-rounded.MuiPaper-elevation8.MuiPopover-paper.css-177ic5c > ul > li:nth-child(4)')
    BUTTON_SUBMIT = (By.XPATH, '/html/body/div[5]/div[3]/div/div[2]/button[1]')
    BUTTON_SAVE = (By.CSS_SELECTOR, '#add-user-dialog-popup > div.MuiDialog-container.MuiDialog-scrollPaper.css-ekeie0 > div > div.MuiDialogActions-root.MuiDialogActions-spacing.add-user__dialog-actions.css-14b29qc > button.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButtonBase-root.sc-jqUVSM.eSNETh.css-1hw9j7s')
    CLICK_LEFT = (By.XPATH, '/html/body/div[1]/div[2]/div/div[3]/div[1]/div[1]/div/img[1]')
    CLICK_RIGHT = (By.XPATH, '/html/body/div[1]/div[2]/div/div[3]/div[1]/div[1]/div/img[2]')
    BUTTON_TODAY = (By.XPATH, '/html/body/div[1]/div[2]/div/div[3]/div[1]/div[4]')
    TEAM_BUTTON = (By.ID, 'teamsSelect')
    NEW_TEAM = (By.ID, 'newTeam')
    INPUT_TEAM_NAME = (By.ID, 'teamName')
    BUTTON_OK = (By.ID, 'createTeamButton')
    BUTTOM_DELETE_TEAM = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/p/div[2]/div/div/img[2]')
    INPUT_DELETE = (By.CSS_SELECTOR, '#\\:r2i\\::')
    BUTTON_SUBMIT_Q = (By.CLASS_NAME, 'MuiOutlinedInput-input MuiInputBase-input css-1x5jdmq')
    BUTTON_CREATE = (By.ID, 'editTeam')
    INPUT_NAME = (By.ID, 'editingTeamName')
    BUTTON_SAVE_NAME = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/p/div/div[2]/img[1]')
    BUTTON_INFO = (By.XPATH, '/html/body/div[1]/div[2]/div/div[1]/div/div[3]/div/div/div/img')
    KNOWLEDGE_BASE = (By.XPATH, '/html/body/div[3]/div[3]/ul/a[1]')
    CONTACT_US = (By.XPATH, '/html/body/div[3]/div[3]/ul/a[2]')
    SUGGEST_FEATURE = (By.XPATH, '/html/body/div[3]/div[3]/ul/a[3]')
    PRODUCT_MAP = (By.XPATH, '/html/body/div[3]/div[3]/ul/a[4]')
    REOPEN = (By.XPATH, '/html/body/div[3]/div[3]/ul/a[5]')
    REAPEN_KNOW = (By.XPATH, '/html/body/div[3]/div[3]/ul/a[6]')
    BUTTON_SETTING = (By.XPATH, '/html/body/div[1]/div[2]/div/div[3]/div[1]/div[7]')
    BUTTON_MOUNTH = (By.XPATH, '/html/body/div[4]/div[3]/div/div/div[5]/div/span/span[8]')
    BUTTON_DAYS = (By.XPATH, '/html/body/div[4]/div[3]/div/div/div[5]/div/span/span[4]')
    BUTTON_WEEK = (By.XPATH, '/html/body/div[4]/div[3]/div/div/div[5]/div/span/span[6]')
    BUTTON_DOWNLOAD = (By.XPATH, '/html/body/div[1]/div[2]/div/div[3]/div[1]/a')
    BUTTON_PRINT_PDF = (By.XPATH, '/html/body/div/div[2]/div/div[1]/div/button/p/div/p')


class ActualsPageLocators:
    CALENDAR_LEFT = (By.XPATH, '/html/body/div[1]/div[2]/div[2]/div[2]/div/img[1]')
    CALENDAR_RIGHT = (By.XPATH, '/html/body/div[1]/div[2]/div[2]/div[2]/div/img[2]')
    ACT_LINK = (By.XPATH, '/html/body/div[1]/div[2]/div/div[1]/div/div[2]/div[1]/a[2]')
    BUTTON_NEXT = (By.CLASS_NAME, 'MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-vubbuv')
    BUT_COPY_PLANNER = (By.XPATH, '/html/body/div[1]/div[2]/div[2]/div[3]/div[1]')
    SELECT_DATA = (By.XPATH, '/html/body/div[4]/div[3]/div/div[1]/div[1]/div/div/input')
    NUMBER = (By.XPATH, '/html/body/div[5]/div[3]/div/div[2]/div[2]/div/div[2]/div[2]/button')
    CHOOSER_USER = (By.CLASS_NAME, 'tb-radio-button')
    BUTTON_SUB = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/button')
    POP_UP_WINDOW_BTN = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/button')
    BUTTON_DOWNLOAD = (By.XPATH, '/html/body/div[1]/div[2]/div[2]/div[3]/div[2]')
    START_DATA = (By.XPATH, '/html/body/div[4]/div[3]/div/div[1]/div[1]/div/div/input')
    NUMBER_2 = (By.XPATH, '/html/body/div[5]/div[3]/div/div[2]/div[2]/div/div[1]/div[6]/button')
    FINISH_DATA = (By.XPATH, '/html/body/div[4]/div[3]/div/div[1]/div[2]/div/div/input')
    FINISH_NUMBER = (By.XPATH, '/html/body/div[5]/div[3]/div/div[2]/div[2]/div/div[2]/div[5]/button')
    BUTTON_OK_SUB = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/button')
    BUTTON_APPRUV_LOGS = (By.XPATH, '/html/body/div[1]/div[2]/div[2]/div[3]/a/div')


class UserPageLocators:
    BUT_CREATE_USER = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/button[3]')
    INPUT_FIRST = (By.ID, 'userFirstName')
    INPUT_LAST = (By.ID,'userLastName')
    INPUT_EMAIL = (By.ID, 'userEmail')
    USER_ROLE = (By.XPATH, '/html/body/div[4]/div[3]/div/div[1]/div[2]/div[3]/div[2]/div/div/div[1]')
    INPUT_PHONE = (By.ID, 'userPhoneNumber')
    BUTTON_SETTING = (By.XPATH, '/html/body/div[4]/div[3]/div/button')
    BUTTON_CREATE = (By.CSS_SELECTOR, '#createUser')
    CHOOSE_USER = (By.XPATH, '/html/body/div[1]/div[2]/div/div[4]/div[2]/div[1]/div/div[2]/p')
    BUTTON_EDIT_USER = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/button')
    INPUT_NUMBER = (By.ID, 'editPhoneNumber')
    BUTTON_SAVE = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/button[1]')
    BUTTON_DELETE = (By.ID, 'deleteUserButton')
    BUTTON_DEACTIVATE = (By.XPATH, '/html/body/div[5]/div[3]/div/div[2]/button[1]')
    BUTTON_MANAGE_TAG = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/button[2]')
    ADD_TAG = (By.ID, 'addTag')
    INPUT_NAME = (By.ID, 'tagName')
    BUTTON_OK = (By.ID, 'createTag')
    BUTTON_EXIT = (By.CSS_SELECTOR, '#form-dialog-title > div > svg')
    DELETE_TAG = (By.ID, 'deleteTag')
    BUTTON_DEL_TAG = (By.XPATH, '/html/body/div[5]/div[3]/div/div[2]/button[1]')
    UPLOAD_USER = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/button[1]')
    BUTTON_CANCEL = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/button[2]')
    INPUT_SEARCH = (By.ID, 'filterUsers')
    USER_VIT = (By.XPATH, '/html/body/div[1]/div[2]/div/div[4]/div[2]/div/div/div[2]/p')


class ProjectPageLocators:
    BUTTON_CREATE_PROJ = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/button')
    INPUT_NAME = (By.ID, 'projectName')
    INPUT_SHOT_NAME = (By.ID, 'projectShortName')
    BIS_UNIT = (By.XPATH, '/html/body/div[4]/div[3]/div/div[1]/div[2]/div[4]/div[2]/p[2]/div/div/div/input')
    DISCRIBLE = (By.XPATH, '/html/body/div[4]/div[3]/div/div[1]/div[2]/div[6]/div/div/div/div[2]/div')
    BUTTON_SAVE = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/button[1]')
    PROJECT_BIS = (By.XPATH, '/html/body/div[1]/div[2]/div/div[4]/div[2]/div[1]/div/div[2]/p')
    EDIT_PROJET = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/button')
    INPUT_HOURS = (By.XPATH, '/html/body/div[4]/div[3]/div/div[1]/div[2]/div[3]/div[1]/p[2]/div/div/div/input')
    BUT_SAVE = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/button[1]')
    SEARCH = (By.ID, 'filterProjects')
    CHECKBOX = (By.XPATH, '/html/body/div[1]/div[2]/div/div[4]/div[2]/div/div/div[1]/input')
    CHECK_BOX_OFF = (By.XPATH, '/html/body/div[1]/div[2]/div/div[4]/div[1]/div[1]/input')
    BUTTON_DELETE = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/img')
    DEL_PROJECT = (By.XPATH, '/html/body/div[5]/div[3]/div/div[2]/button[1]')
    MANAGE_CLIENTS = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/button[2]')
    ADD = (By.XPATH, '/html/body/div[4]/div[3]/div/div[1]/div[1]/div[1]/img')
    INPUT_NAME_CLIENT = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div/div[1]/div[1]/div/div/div/input')
    EMAIL_CLIENT = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div/div[1]/div[2]/div/div/div/input')
    CLICK_OK_CLIENT = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div/div[1]/div[4]/img[1]')
    EDIT_CLIENT = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div[2]/div[1]/div[4]/div/img[1]')
    INPUT_PHONE_CLIENT = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div[2]/div[1]/div[3]/div/div/div/input')
    EDIT_SAVE = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div[2]/div[1]/div[4]/img[1]')
    DEL_CLIENT = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div[2]/div[1]/div[4]/div/img[2]')
    DELETE_OK_CLIEN = (By.XPATH, '/html/body/div[5]/div[3]/div/div[2]/button[1]')
    UPLOAD_PROJECT = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/button[1]')
    INPUT_COMMENT = (By.XPATH, '/html/body/div[4]/div[3]/div/div[1]/p/div/div/textarea[1]')
    CANCEL_UPLOAD = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/button[2]')


class ProfilePageLocators:
    EDIT = (By.CSS_SELECTOR, '#root > div.App > div > div.sc-cLFqLo.eEvALQ.col-md-8.offset-md-2.row > div.sc-kjEcyX.FYQZI.col-md-9 > div > div.sc-gUAEMC.cgNRaA > button')
    FIRST_NAME = (By.ID, 'firstName')
    BUTTON_EMAIL_PASS = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[1]/div[2]/div[2]')
    OLD_PASS = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div[2]/div/div[1]/div/div/div/div/input')
    NEW_PASS = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div[2]/div/div[2]/div[1]/div/div/div/input')
    CONF_NEW_PASS = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/div/div/div/input')
    BUTTON_UPDATE = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div[2]/div/div[3]/button')
    BUTTON_SHEDULE = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[1]/div[2]/div[3]')
    INPUT_FRI = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div/div[5]/div/div/div/input')
    BUTTON_SAVE = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/button')
    BUTTON_NOTIFICATION = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[1]/div[2]/div[4]')
    RADIO_BUTTON_1 = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div/div[2]/div/img')
    RADIO_BUTTON_2 = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div/div[3]/div/img')
    RADIO_BUTTON_FIRST = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div/div[1]/div/img')
    BUTTON_SAVE_1 = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/button')
    BUTTON_EDIT = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div[3]/button')
    INPUT_PHONE = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/div/div[1]/div[3]/div/div/div/input')
    BUTTON_SAVE_2 = (By.XPATH, '/html/body/div[1]/div[2]/div/div[2]/div[2]/div/button[2]')